---
title: "ASSIGNMENT 7"
author: "Siddhartha Bhaumik"
date: '2022-05-06'
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Add Citations

-   R for Everyone
-   Discovering Statistics Using R

## Load libraries

```{r echo=FALSE}
library(ggplot2)
library(ppcor)
theme_set(theme_minimal())
```

```{r echo=TRUE}
## Load the `data/r4ds/heights.csv` to
heights_df <- read.csv("/Users/siddharthabhaumik/Documents/GitHub/dsc520/data/r4ds/heights.csv")

## Viewing Sample data
head(heights_df)

# Fit a linear model
earn_lm <-  lm(earn ~ ed + race + height + age + sex , data=heights_df)

# View the summary of your model
summary(earn_lm)

# New data frame
predicted_df <- data.frame(
  earn = predict(earn_lm, heights_df),
  ed=heights_df$ed, race=heights_df$race, height=heights_df$height,
  age=heights_df$age, sex=heights_df$sex
)

## Compute deviation (i.e. residuals)
mean_earn <- mean(heights_df$earn)

## Corrected Sum of Squares Total
sst <- sum((mean_earn - heights_df$earn)^2)

## Corrected Sum of Squares for Model
ssm <- sum((mean_earn - predicted_df$earn)^2)

## Residuals
residuals <- (heights_df$earn - predicted_df$earn)

## Sum of Squares for Error
sse <- sum(residuals^2)

## R Squared
r_squared <- (ssm/sst)

print(r_squared)

## Number of observations
n <- nrow(heights_df)

## Number of regression paramaters
p <- 8

## Corrected Degrees of Freedom for Model
dfm <- (p-1)

## Degrees of Freedom for Error
dfe <- (n-p)

## Corrected Degrees of Freedom Total:   DFT = n - 1
dft <- (n-1)

## Mean of Squares for Model:   MSM = SSM / DFM
msm <- (ssm/dfm)

## Mean of Squares for Error:   MSE = SSE / DFE
mse <- (sse/dfe)

## Mean of Squares Total:   MST = SST / DFT
mst <- (sst/dft)

## F Statistic
f_score <- (msm/mse)

print(f_score)

## Adjusted R Squared R2 = 1 - (1 - R2)(n - 1) / (n - p)
adjusted_r_squared <- (1 - (1 - r_squared)*(n - 1) / (n - p))

print(adjusted_r_squared)

```
